// <auto-generated />
using DataBase_Website.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBase_Website.Migrations
{
    [DbContext(typeof(DataBase_WebsiteContext))]
    [Migration("20220326223946_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataBase_Website.Models.DataBaseModels.AccountModel", b =>
                {
                    b.Property<string>("PrivateAccountKey")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PrivateAccountKey");

                    b.ToTable("AccountModel");
                });

            modelBuilder.Entity("DataBase_Website.Models.DataBaseModels.JobModel", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignedAccounts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedImages")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.ToTable("JobModel");
                });
#pragma warning restore 612, 618
        }
    }
}
